name: Deployment Build

on:
  push:
    branches: ["main"]

jobs:
  build_android:
    type: build
    params:
      platform: android

  deploy:
    type: deploy
    name: Deployment Build
    environment: production
    params:
      prod: true
