name: Deploy to EAS Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Check EXPO_TOKEN is set
        run: |
          echo "Token length: ${#EXPO_TOKEN}"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Web App
        run: eas build --platform web --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Deploy to EAS Hosting
        run: eas deploy --platform web --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}